nolanfrb/42sh

- .gitignore
- Makefile
- tests/lexer/test_check_special_token.c
- tests/lexer/test_count_words.c
- tests/lexer/test_extract_word.c
- tests/lexer/test_handle_delimiter.c
- tests/lexer/test_handle_special_token.c
- tests/lexer/test_lexer.c
- tests_src.list
This pull request includes several changes aimed at improving the test coverage for the lexer component of the project. The most significant changes involve adding new test cases for various lexer functions and updating the `Makefile` to refine the build configuration.
* Added new test cases for `check_special_token` in `tests/lexer/test_check_special_token.c` to verify the handling of special tokens and their positions.
* Added new test cases for `count_words` in `tests/lexer/test_count_words.c` to ensure accurate word counting, including handling multiple spaces and special tokens.
* Added new test cases for `extract_word` in `tests/lexer/test_extract_word.c` to validate correct substring extraction from different positions.
* Added new test cases for `handle_delimiter` in …
> Lexer Test Coverage

- include/env.h
- include/shell.h
- src.list
- src/env/env_free.c
- src/env/env_get.c
- src/env/env_init.c
- src/env/env_set.c
- src/env/env_unset.c
- tests/env/test_env_free.c
- tests/env/test_env_get.c
- tests/env/test_env_init.c
- tests/env/test_env_set.c
- tests/env/test_env_unset.c
- tests_src.list
This pull request introduces a series of changes to enhance the environment variable handling in the shell project. The changes include adding new functionality for managing environment variables, updating existing structures, and adding tests for the new functions.
* **New functions for environment management**:
- Added `free_shell`, `get_env_value`, `init_shell`, `set_env_value`, and `unset_env_value` functions to `include/env.h` for managing environment variables.
- Implemented `free_shell` in `src/env/env_free.c` to release memory allocated for the shell structure and its environment variables.
- Implemented `get_env_value` in `src/env/env_get.c` to retrieve the value of a specified environment variable.
- Implemented `init_shell` in `src/env/env_init.c` to initialize the shell …
> Add Environment Variable Management: Core Functions and Unit Tests

- include/shell.h
- src.list
- src/main.c
- src/main_loop/handle_user_input.c
- src/main_loop/process_command.c
This pull request introduces significant changes to the `42sh` project, primarily focusing on the implementation of a main loop for handling user input and processing commands. The key changes include the addition of new functions for reading commands, building AST structures, and processing commands, as well as modifications to the main function to integrate these new functionalities.
* **Addition of `main_loop` function**: Introduced a new `main_loop` function in `src/main.c` to handle the interactive shell prompt, read user input, and build AST structures.
* **Display prompt function**: Added a `display_prompt` function to show the shell prompt to the user.
* **New functions in `include/shell.h`**: Added declarations for `built_ast_struct`, `process_command`, and `read_command` …
> feat(main loop): add commands execution

- include/env.h
- include/shell.h
- src.list
- src/env/env_free.c
- src/env/env_get.c
- src/env/env_init.c
- src/env/env_set.c
- src/env/env_unset.c
- src/env/local_get.c
- src/env/local_set.c
- src/env/local_unset.c
- tests/env/test_env_free.c
- tests/env/test_env_get.c
- tests/env/test_env_init.c
- tests/env/test_env_set.c
- tests/env/test_env_unset.c
- tests/env/test_local_get.c
- tests/env/test_local_set.c
- tests/env/test_local_unset.c
- tests_src.list
This pull request introduces significant changes to the environment management in the shell project. It includes the addition of new functions for handling environment variables and local variables, updates to the shell structure, and corresponding test cases to ensure functionality. The most important changes are summarized below:
* [`include/env.h`](diffhunk://#diff-a419e7596371d6c7b61b92909c2206bc29f9f8de7ccdb6b5d2eec9712539175fR1-R22): Added declarations for new functions to manage environment and local variables, such as `free_shell`, `get_env_value`, `set_env_value`, `unset_env_value`, `get_local_value`, `set_local_value`, and `unset_local_value`.
* [`include/shell.h`](diffhunk://#diff-27d16b23443749eb94db58305d3c6c13b9b251dc1551f00e587d10754e1d31a8L28-R31): Updated the `shell_s` …
> Add Local Variable Management Support to Shell with Unit Tests

- include/ast.h
- src/main_loop/process_command.c
This pull request includes changes to the `include/ast.h` and `src/main_loop/process_command.c` files to refactor the way execute functions are handled and improve the structure of the code.
Refactoring of execute functions:
* [`include/ast.h`](diffhunk://#diff-0e94326f4ee73cf3526bc77ef5dca7bc74a919aa7ddd33eff55e04a251090bc1L77-L87): Removed the declaration of the `execute_functions` array and the commented-out function assignments.
* [`src/main_loop/process_command.c`](diffhunk://#diff-a0ee54e7a7b25cb7408c5c894298d4045389caed344220a980ef3f7693afa273L11-L24): Moved the `execute_functions` array inside the `process_command` function and changed its declaration to `static`. Removed the commented-out function assignments.
> refactor(execute_functions): redeclaration of execute_function array

- src/command_execution/execute_pipe_command.c
Correct waitpid call to use the last command's PID in pipe execution.
The problem was that sometimes, the prompt was printed before the result of the last command in the pipe segment.
> fix(execute_pipe_command) : Fix waitpid placement in the function

- Makefile
- include/shell.h
- src/builtins/builtin_cd.c
- src/builtins/builtin_echo.c
- src/builtins/builtin_setenv.c
- src/builtins/builtin_unsetenv.c
- src/builtins/echo_utils.c
- src/env/env_free.c
- src/utils/printf_flush.c
- src_for_tests.list
- tests/builtins/test_builtin_cd.c
- tests/builtins/test_builtin_echo.c
- tests/builtins/test_builtin_env.c
- tests/builtins/test_builtin_exit.c
- tests/builtins/test_builtin_setenv.c
- tests/builtins/test_builtin_unsetenv.c
- tests/builtins/test_builtins.c
- tests/builtins/test_echo_utils.c
- tests/env/test_env_free.c
- tests_src.list
This pull request introduces several key updates to the codebase, including the addition of a new `printf_flush` utility function, significant refactoring of built-in commands to use this utility, improvements to the `Makefile` for test coverage, and the addition of comprehensive unit tests for built-in commands. These changes aim to improve code maintainability, ensure proper flushing of output, and enhance test coverage.
* Added a new `printf_flush` function in `src/utils/printf_flush.c` to ensure that printed output is immediately flushed to `stdout`. This function wraps `vprintf` and `fflush` for consistent behavior across the codebase.
* Replaced all instances of `printf` with `printf_flush` across multiple built-in commands (`builtin_cd`, `builtin_echo`, `builtin_setenv`, …
> refactor(builtins): use printf_flush for consistent output and add unit tests

- include/command.h
- src.list
- src/command_execution/execute_subshell_command.c
- src/main_loop/process_command.c
- src_for_tests.list
This pull request introduces support for executing subshell commands in the shell implementation. The main changes include adding a new function to handle subshell execution, updating the AST node processing logic, and registering the new functionality in the build system.
* Added the `execute_subshell_command` function in `src/command_execution/execute_subshell_command.c` to handle the execution of subshell commands. This function forks a new process to execute the subshell, manages the exit status, and updates the shell's state accordingly.
* Declared the `execute_subshell_command` function in the `command.h` header file to make it accessible throughout the project.
* Updated the `process_command` function in `src/main_loop/process_command.c` to include a new case for `NODE_SUBSHELL`, …
> feat(command): add subshell command execution functionality

- include/shell.h
- src/command_execution/execute_command.c
- src/command_execution/pipe/execute_pipe_command.c
- src/main.c
- src/main_loop/handle_user_input.c
- src/parser/parse_redirect.c
This pull request introduces several updates to improve error handling, enhance code modularity, and refine process management in the shell application. Key changes include adding error handling for user input and AST parsing, refactoring child process management for better exit code handling, and improving modularity by introducing helper functions. Below is a categorized summary of the most important changes:
* Refactored `built_ast_struct` to include `shell_t *shell_info` for better error handling and to set the shell's `exit_code` on errors. Introduced a helper function `handle_user_input_errors` to streamline error handling for tokenization and lexing (`src/main_loop/handle_user_input.c`).
* Updated error message in `process_redirect_node` to make it like …
> refactor: update built_ast_struct to accept shell_info and improve error handling

- include/globbings.h
- src.list
- src/command_execution/execute_command.c
- src/globbings/get_directory.c
- src/globbings/get_file.c
- src/globbings/globbings.c
- src/main.c
- src_for_tests.list
- tester/test_main.c
- tests/globbings/test_globbings_getdirectory.c
- tests/globbings/test_globbings_getfiles.c
- tests/globbings/test_globbings_main_function.c
- tests_src.list
This pull request introduces a new feature for handling globbing patterns in the shell, including the implementation of several utility functions and integration into the main execution flow. The most significant changes involve adding the `globbings` module, which processes wildcard patterns in command arguments, and modifying the main loop to utilize this new functionality.
* **Header File for Globbing**: Added `globbings.h` to define the `globbings` module's interface and its supporting structures and functions. This includes functions for retrieving files, processing directories, and freeing resources. (`include/globbings.h`)
* **Core Globbing Logic**: Implemented the `globbings` function in `globbings.c` to replace command arguments containing globbing patterns (e.g., `*`, `?`) with …
> feat(globbings): implement file globbing functionality

- src/command_execution/execute_and_command.c
This pull request refines the logic in the `execute_and` function to improve clarity and ensure the correct exit code is returned. 
Key changes:
* [`src/command_execution/execute_and_command.c`](diffhunk://#diff-45e1afbb8ec438b8068fd662cc3c2974d9fb88609774193cb69c59929e4755efL13-R17): Introduced a local variable `exit_code` to store the result of `process_command` for the left operand. This ensures that the function returns the correct exit code when the left operand fails, rather than always returning `-1`.
> fix(command_execution): update execute_and function to return the exit code of the first command

- tests/parser/tests_ast_build.c
- tests/utils/tests_strcat.c
- tests_src.list
This pull request introduces unit tests for two key functionalities (`read_command` and `build_ast_struct`) and a utility function (`my_strcat`). It also updates the test suite configuration to include these new test files. Below is a summary of the most important changes:
* [`tests/parser/tests_ast_build.c`](diffhunk://#diff-239e0d8b4358506e6e0730b42e592b0a10e0924b3474a7789d04da793a789455R1-R85): Added tests for `read_command` to validate handling of simple input and EOF scenarios. Tests for `build_ast_struct` were also added to ensure correct AST creation for valid, empty, and invalid inputs.
* [`tests/utils/tests_strcat.c`](diffhunk://#diff-8795912cc487a036e5983ee490cd61467ff3509ca4657b533f2e661d53cb5fe6R1-R51): Introduced tests for `my_strcat` to verify basic concatenation, handling …
> tests: add ast building and command reading test

- src/command_execution/pipe/execute_pipe_command.c
- tests/tests
This pull request refactors the pipe execution logic in `execute_pipe_command.c` to improve clarity and modularity, and adds new test cases to validate the changes. The most important changes include splitting and reorganizing pipe and process management functions, modifying the handling of built-in commands, and introducing test cases for edge scenarios.
* Removed the `close_pipes` function and replaced it with more specific functions: `close_parent_pipes` and `setup_child_pipes`, to handle pipe closure in a more modular way. (`src/command_execution/pipe/execute_pipe_command.c`, [src/command_execution/pipe/execute_pipe_command.cL18-R112](diffhunk://#diff-2573da8a1859025491e975b7ea8f6732e4e0620475bb60bd73a0b27645b809f0L18-R112))
* Introduced `create_pipe_if_needed` and `handle_fork_error` …
> fix(pipe): fix cleaning pipe at run time

- include/env.h
- src.list
- src/builtins/builtin_env.c
- src/command_execution/get_command_path.c
- src/command_execution/utils/path.c
- src_for_tests.list
This pull request introduces functionality to retrieve environment variables and refactors how the `PATH` environment variable is handled in the shell. The most significant changes include the addition of utility functions for environment variable access, integration of these functions into command path resolution, and the necessary updates to include files and build configuration.
* Added `my_getenv` function to retrieve the value of an environment variable from a given environment array. (`src/builtins/builtin_env.c`, [src/builtins/builtin_env.cR13-R22](diffhunk://#diff-de295ba2ebe8c3aa5443e5d2cd9b83fce3c7b47073bb69ad02ebe68beb51c3edR13-R22))
* Added `get_path` function to retrieve the `PATH` environment variable, with a fallback to `DEFAULT_PATH` if it is not set. …
> hotfix(path_handling): handle path environnement variable on /commands

- .github/workflows/tester.yml
This pull request includes a small update to the `.github/workflows/tester.yml` file. The change ensures that the test output is displayed in the logs when tests fail, making it easier to diagnose issues.
> fix(tester): display test output on failure for better debugging

- src/builtins/echo_utils.c
This pull request introduces a change to the `print_env_variable` function in `src/builtins/echo_utils.c` to handle the special case of the `$?` variable, which represents the shell's exit code. The most important change is the addition of logic to check for `$?` and print the exit code directly.
* [`src/builtins/echo_utils.c`](diffhunk://#diff-f09757f101387294380ac1db3dd79e350295ca944da293f85f7adf6979ffca99L63-R69): Updated the `print_env_variable` function to handle the `$?` variable. If `$?` is detected, the function now prints the shell's exit code and skips the call to `get_env_value`. This ensures proper handling of this special variable.
> fix(print_env_variable): improve handling of special variable '$?'

- tests/tests
This pull request adds a variety of new test cases to the `tests/tests` file, enhancing coverage across multiple shell functionalities. The changes include tests for environment variable handling, operator precedence, subshell behavior, inhibitors, heredoc usage, and globbing patterns. Below is a categorized summary of the most important additions:
* Added tests for setting environment variables with special characters and pipes, as well as operator precedence and mixed logical conditions. (`[[1]](diffhunk://#diff-443539a197ffddd0393a0750e4d34f721f14b047c603b938ebf883c60b3710edR230-R237)`, `[[2]](diffhunk://#diff-443539a197ffddd0393a0750e4d34f721f14b047c603b938ebf883c60b3710edR577-R584)`, `[[3]](diffhunk://#diff-443539a197ffddd0393a0750e4d34f721f14b047c603b938ebf883c60b3710edR844-R859)`) …
> test(tests): add new test cases for setenv, subshells, and heredoc features

- include/line_editing.h
- include/shell.h
- src/builtins/builtin_exit.c
- src/line_editing/handlers.c
- src/line_editing/read_command_line.c
- src/line_editing/terminal_control.c
This pull request introduces changes to improve the handling of dynamic buffer resizing and memory management in the shell's line editing functionality. The key updates include transitioning from a single `char *buffer` to a double pointer `char **buffer` for better flexibility, adding dynamic buffer reallocation logic, and introducing a `buffer_capacity` field in the `shell_t` structure to track buffer size. These changes enhance the robustness and scalability of the command-line interface.
* Updated function signatures in `include/line_editing.h` to use `char **buffer` instead of `char *buffer`, enabling dynamic buffer management. [[1]](diffhunk://#diff-bc152e836a67453bf6b35a9fb2857b97ee6e84f2be2087903ff77b367de30c76L15-R15) [[2]](diffhunk://#diff-bc152e836a67453bf6b35a9fb2857b97ee6e84f2 …
> fix: memory corruption due to buffer clearing

- include/shell.h
- src.list
- src/builtins/builtin_env.c
- src/main.c
- src/utils/display_prompt.c
- src/utils/gethostname.c
- src_for_tests.list
This pull request introduces a new dynamic prompt feature for the shell, enhancing user experience by displaying the hostname and current directory in the prompt. Key changes include the addition of the `display_prompt` and `my_gethostname` utilities, modifications to integrate the new prompt functionality, and a bug fix in the `my_getenv` function.
* Added `display_prompt` function to dynamically generate a shell prompt with the hostname and current directory, supporting tilde expansion for the home directory. (`src/utils/display_prompt.c`, [src/utils/display_prompt.cR1-R48](diffhunk://#diff-d2907471b00c5e3f5bd438be5c4a0a69739e1cec73c339cdffe61767522d43ffR1-R48))
* Introduced `my_gethostname` function to retrieve the system hostname from `/etc/hostname`. (`src/utils/gethostname.c`, …
> feat(prompt): add dynamic prompt with hostname and current directory

- src/line_editing/handlers.c
- src/utils/gethostname.c
This pull request includes updates to improve prompt handling in history navigation and standardize hostname behavior. The most important changes are grouped below by theme:
* Updated `handle_history_up` and `handle_history_down` in `src/line_editing/handlers.c` to replace `write_prompt()` with a combination of clearing the current line (`write(STDOUT_FILENO, "\r* Updated `handle_history_up` and `handle_history_down` in `src/line_editing/handlers.c` to replace `write_prompt()` with a combination of clearing the current line (`write(STDOUT_FILENO, "\r\033[K", 4)`) and calling `display_prompt()` for better visual consistency. ([src/line_editing/handlers.cL77-R78](diffhunk://#diff-da455a6482002d1d063464f9946d530c2c8c3ae0a0c37fc35ade5e94568fb4efL77-R78), …
> fix(shell): improve prompt handling and standardize hostname fallback

- src/line_editing/handlers.c
This pull request removes an unused function from the `handlers.c` file, simplifying the codebase.
Codebase simplification:
* [`src/line_editing/handlers.c`](diffhunk://#diff-da455a6482002d1d063464f9946d530c2c8c3ae0a0c37fc35ade5e94568fb4efL20-L24): Removed the unused `write_prompt` function, which was responsible for writing a prompt to the terminal. This function was no longer being called anywhere in the code.
> refactor(handlers): remove unused write_prompt function
